import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import Menu from './Menu';
import ReactSearchBox from "react-search-box";
import data from './data.json' assert {type: 'json'};

function Buildings_repr({ list }) {
  /*console.log(list)*/
  return (
    <div>
      <h2>known Buildings </h2>
      <ul>
        {list.map((building) => (
          <li key={building._id}>Nom :  {building.name} id : {building._id}</li>
        ))}
      </ul>
    </div>
  );
}

export default function Home() {
  const [buildings, setBuildings] = useState([]);

  const [selectedItem, setSelectedItem] = useState(1);
  

  
  useEffect(() => {
    fetch('http://localhost:5000/api/buildings/list')
      .then((res) => res.json())
      .then((data) => {
        setBuildings(data.buildings??[]);
      });

  }, []);
  const menuItems = ['Hauteur', 'DPE', 'Année construction', 'superficie'];
  const [activeItem, setActiveItem] = useState(0);
  

  return (
    <>      <Head>
        <title>Example Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Example of page</h1>
        <Buildings_repr list={buildings} />
      
    
    <h2>scrolling menu</h2>
    <div>
      <Menu
        items={menuItems}
        activeItem={activeItem}
        setActiveItem={setActiveItem}

      />
      {/* Render the rest of your app components here */}
    </div>
    <h3>option chosen: </h3>
    <li>{menuItems[activeItem]}</li>
    <h4>search bar</h4>
    <ReactSearchBox
        placeholder="rechercher pays"
        
        data={data}
        callback={(record) => console.log(record)}
      />

    
      </main>

        
        
        
    </>
  );}