import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import Menu from './Menu';
import ReactSearchBox from "react-search-box";
import data from './data.json' assert {type: 'json'};
const host_name = 'http://localhost:5000/api/';
const site_name = 'http://localhost:3000/';
function Buildings_repr({ list }) {
  
  return (
    <div>
      <h2>known Buildings </h2>
      <ul>
        {list.map((building) => (
          <li key={building._id}>Nom :  {building.name} id : {building._id}</li>
        ))}
      </ul>
    </div>
  );
}

const sendData = async (data) => {
  const response = await fetch('http://localhost:5000/api/receive', {
     
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'

    },
    body: JSON.stringify(data),
  })
  .then((res) => res.json())
  .then((data) => console.log(data))
  .catch((err) =>   console.error(err));
  
  const responseData = await response.json();
  return responseData;
};

export default function Home() {
  const [buildings, setBuildings] = useState([]);

  const [selectedItem, setSelectedItem] = useState(1);
  

  
  useEffect(() => {
    fetch('http://localhost:5000/api/buildings/list')
      .then((res) => res.json())
      .then((data) => {
        setBuildings(data.buildings??[]);
      });

  }, []);
  const menuItems = ['Hauteur', 'DPE', 'Année construction', 'superficie'];
  const [activeItem, setActiveItem] = useState(0);
  const [searchQuery, setSearchQuery] = useState('');

  /*pour la barre de recherche maintenant*/

  const onSelect = (selected) => {
    const figure = data.find((figure) => figure.id === selected.id);
    setSelectedItem(figure);
    sendData(figure);
    
  };

  const handleSearchInputChange = (value) => {
    setSearchQuery(value);
  };
  const filteredFigures = data.filter((figure) =>
    figure.value.toLowerCase().includes(searchQuery.toLowerCase())
  );
  



  return (
    <>      <Head>
        <title>Example Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <Buildings_repr list={buildings} />
      
    
    <h2>scrolling menu</h2>
    <div>
      <Menu
        items={menuItems}
        activeItem={activeItem}
        setActiveItem={setActiveItem}

      />
      {}
    </div>
    <h3>option chosen: </h3>
    <li>{menuItems[activeItem]    }</li>
    <h4>search bar</h4>
    <ReactSearchBox
        placeholder="rechercher pays"
    
        data={data}
        onSelect={onSelect}
        onChange={handleSearchInputChange}
      />
      <ul>
        {filteredFigures.map((figure) => (
          <li key={figure.id}>
            {figure.value} ({figure.continent})
          </li>
        ))}
      </ul>

    
      </main>

        
        
        
    </>
  );}